autoDetectedPackages:
- ai.spring.demo.ai.playground
- com.alibaba.cloud.ai.example.audio
- com.alibaba.cloud.ai.example.chat.dashscope
- com.alibaba.cloud.ai.example.chat.deepseek
- com.alibaba.cloud.ai.example.chat.ollama
- com.alibaba.cloud.ai.example.chat.openai
- com.alibaba.cloud.ai.example.helloworld
- com.alibaba.cloud.ai.example.image.dashscope
- com.alibaba.cloud.ai.example.image.openai
- com.alibaba.cloud.ai.example.multi
- com.alibaba.cloud.ai.example.nacos
- com.alibaba.cloud.ai.example.observability
- com.alibaba.cloud.ai.example.outparser
- com.alibaba.cloud.ai.example.prompt
- com.alibaba.cloud.ai.example.rag
- com.alibaba.cloud.ai.observationhandlerexample
- org.springframework.ai.mcp.samples.filesystem
- org.springframework.ai.mcp.samples.sqlite
enableAutoDetect: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipNonProjectPackages: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
sourceDisplayConfig:
  color: blue
startOnDebug: false
